### ISSUE TITLE
Publishing packages in pipy

### ISSUE THREAD

**Issue by mxochicale** [UCL-ARC/python-tooling#110]
Users might consider to publish their package distributions in PyPI and conda-forge, so I am opening this one listing few initial steps.  

1. Let's start building, installing and checking your package locally:
```
python -m build
pip install -e .
twine check dist/*
```
2. Register an account in [pipy](https://pypi.org/account/register/) and create new package in pipy (project name, owner, repository name, workflow name, env name)
Related references:
     * https://realpython.com/pypi-publish-python-package/
3. Then a bit of CI automation will be required. 
The following is a potential example
```
- name: Build wheel
  run: |
    python setup.py bdist_wheel
- name: Publish package if tagged release
  if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
  uses: pypa/gh-action-pypi-publish@master
  # You need to generate a PYPI API token and add it to your GitHub secrets
  with:
    user: __token__
    password: ${{ secrets.PYPI_API_TOKEN }}
```
Related references:
     * https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

4. Tag and publish release with commit message 
It's worthwhile to add release cycle versions (schedules for alpha, beta, RC and full bugfix support). See how [python versions](https://peps.python.org/pep-0602) are done.
```
git tag -a v0.0.0 -m "First release"
git push origin v0.0.0
```

5. We might also consider to publish our package in conda-forge and automatise its workflow.
Related references:
     * https://blog.gishub.org/how-to-publish-a-python-package-on-conda-forge

### Other references 
https://realpython.com/pypi-publish-python-package/
