### ISSUE TITLE
Versioning the template.

### ISSUE THREAD

**Issue by samcunliffe** [UCL-ARC/python-tooling#260]
@matt-graham says we will get the latest commit at the HEAD of main unless specified.
- [x] verify this

Make a latest tag.

**Comment by paddyroddy** [comment]
I have a workflow for tracking tags https://github.com/paddyroddy/.github/blob/main/.github/workflows/tags.yml

**Comment by paddyroddy** [comment]
Things to do:
- [ ] Make a release (Blocked by #16)
- [x] Add a tracking `latest` tag, which auto updates
- [x] Document `--checkout latest` every we refer to it
- [x] Update bug template #issue #263

**Comment by samcunliffe** [comment]
# Notes from hackmorning 2024-10-22

## Discussion

We discussed options and looked at how [MIRSG have set things up](https://github.com/UCL-MIRSG/.github/blob/2c76880ceb86f4575a103cf66b285c929c364891/.github/workflows/tags.yaml#L42). Their infrastructure is a bit more fancy: they have an auto-updating tag `v0` that always points to the newest `v0.x`. 

We don't need a major version following tag, we want a `latest` tag that follows the latest version (major or minor).

Sam's sketch of what we want (probably doesn't actually work as written...)
```yml
on:
    release:
        types:
            - created

jobs:
    update-tag:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source
              uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

            - name: Set up git
              run: git config --global user.email "ACTIONS BOT"

            - name: Update "latest" tag to point to the newest release
              run: git tag -f latest $GITHUB_SHA && git push --tags
```

## Summary

Auto-updating `latest` tag pointing to the SHA of the newest release tag.

## Decision

@paddyroddy will create a short GitHub action that runs on a release, takes the SHA of the release tag and runs a `git tag -f latest` to (re)create and push a `"latest"` tag.  Then we can have instructions in `README.md` that point to latest.
