### ISSUE TITLE
Add recommendation on how to run `tox` in CI

### ISSUE THREAD

**Issue by paddyroddy** [UCL-ARC/python-tooling#461]
### Which Section of the Documentation Needs Improving?

http://github-pages.arc.ucl.ac.uk/python-tooling/pages/testing.html#test-runners

### What Can be Improved About This Section

i.e. https://github.com/tox-dev/tox-gh as introduced in #460

**Comment by p-j-smith** [comment]
If you're using some features of `uv` (such as some of the [alternative dependency sources](https://docs.astral.sh/uv/concepts/projects/dependencies/#dependency-sources)), you will need to use [`tox-uv`](https://github.com/tox-dev/tox-uv) too. One way is to also use [`astral-sh/setup-uv`](https://github.com/astral-sh/setup-uv) and `uv run`:

```yaml
      - name: Setup uv
        uses: astral-sh/setup-uv@f0ec1fc3b38f5e7cd731bb6ce540c5af426746bb # v6
        with:
          python-version: "3.11"
          enable-cache: true
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock
            **/.tox/**/*

      - name: Test with tox
        run: uv run --with tox-uv tox run
```
